name: Lunaris

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Visual Studio Environment
      shell: cmd
      run: |
        :: En güncel VS 2022 yolunu vswhere ile al
        for /f "usebackq tokens=*" %%i in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -property installationPath`) do set VS_PATH=%%i
        if not defined VS_PATH (
          echo ERROR: Visual Studio not found
          exit /b 1
        )
        echo VS found: %VS_PATH%
        call "%VS_PATH%\VC\Auxiliary\Build\vcvarsall.bat" x64

        :: Build
        cl /EHsc src\*.cpp /Fe:build\*.exe

    - name: Run Rasterizer
      run: .\run.bat
      shell: cmd

    - name: Upload Render Output
      uses: actions/upload-artifact@v4
      with:
        name: Lunaris-Render
        path: build\*.tga
        if-no-files-found: ignore