name: Lunaris

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # MSVC v 
    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '17.5'   # VS 2022

    # Build Project
    - name: Build Project
      run: .\build.bat
      shell: cmd

    # Run Rasterizer
    - name: Run Rasterizer
      run: .\run.bat
      shell: cmd

    # Upload Render Output
    - name: Upload Render Output
      uses: actions/upload-artifact@v4
      with:
        name: Lunaris-Render
        path: build\*.tga
        if-no-files-found: ignore